version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: db_WireWave
    environment:
      POSTGRES_PASSWORD: 123456
    ports:
      - "5433:5432"
    networks:
      - backend_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_WireWave
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - backend_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_WireWave
    ports:
      - "3000:3000"
    networks:
      - backend_network

networks:
  backend_network:
