spring.application.name=wirewave
management.endpoints.web.exposure.include=health, info
management.info.env.enabled=true
info.app.name=wirewave
info.app.description=This is a spring boot for an online store
info.app.version=1.0